### ISSUE TITLE
Any way to distinguish between two tilts that are the same color?

### ISSUE THREAD

**Issue by MattL-NZ** [myoung34/tilty#16]
Hi

I am testing the tilt devices out and want to use them in large quantities (more than the 8 colours).
Is there a way using your system to monitor more than one of the same colour (e.g. two yellow tilts).

I understand that they have different UUID but thought there might be a way around it.

Thanks

**Comment by myoung34** [comment]
AFAIK there isn't.

The point of the UUID is to distinguish the tilt device, and the point of having multiple colors is to distinguish them that way.

A black tilt will always broadcast the same UUID as other black tilts etc.

If you want to track multiple tilts you should use different colors. You _could_ potentially track them by the mac address but that's not currently supported in my library. You could open and scope a feature request to publish the mac address outwards to the emitter, I think that would be doable

**Comment by myoung34** [comment]
@MattL-NZ thoughts on https://github.com/myoung34/tilty/pull/17 ?

**Comment by MattL-NZ** [comment]
@myoung34 I haven't actually setup Tilty yet. Can have a play this evening with my Raspberry Pi.
So is this now using the Mac Address to get the values from the Tilt hydrometer? Would this still work however if both devices have different Mac Addresses but will still have the same UUID.

**Comment by myoung34** [comment]
This will work if you set up your tracking correctly.

Basically in addition to tagging/submitting the color (based on a non-unique UUID) it will also tag the mac address which is unique per device (per fcc)

**Comment by myoung34** [comment]
Also i should clarify: this does **not** change the behavior. Tilt's are still distinguished by color. This just adds payload options to _additionally_ "tag" (this is contextual to the emitter) them with the mac **as well as** the color. Color would still be a first class known entity. Mac would just be "something else there also"

**Comment by MattL-NZ** [comment]
Yeah so we are looking to run around 20 of these devices. 
If we can tag them with a Mac Address, that would be good. Would also be good if we could change the name to be Black1, Black2 Black3 for example.

Also, do we have the ability to log all the data to Google Sheets?

**Comment by myoung34** [comment]
if you use Zapier, yes =)

Otherwise, not at this time, no. Just webhooks (of nearly any kind), datadog, brewstat, influx

I've thought about doing that, but the oauth flow from a CLI isn't very user friendly.
