### ISSUE TITLE
Tilty always uses 100% CPU

### ISSUE THREAD

**Issue by ozamosi** [myoung34/tilty#31]
The last 2 lines in cli.py creates an infinite loop that busy-waits, which will always try to use up one complete CPU core. This causes my raspberry pi to become hot.

I considered a lazy solution of just replacing the pass with sleep, but then I'm a bit confused why that thread needs to exist at all.

**Comment by myoung34** [comment]
Do you have any captures that I can see? I don't remember this ever being an issue since this is single core threaded
