### ISSUE TITLE
Set and use calibration information

### ISSUE THREAD

**Issue by x3dfxjunkie** [myoung34/tilty#42]
I've found that my Tilt is off slightly when calibrated in filtered water. The Tilt iOS app takes this into account, but this project does not seem to do the same. I'm not sure if this would be as simple as adding an offset when pulling the current gravity.

**Comment by myoung34** [comment]
Ironically I added this in the dashboard and forgot to allow that here.

I'll see what I can do shortly.

**Comment by myoung34** [comment]
@x3dfxjunkie you can now do this in the config:

```ini
[general]
gravity_offset = -0.001 # subtract 0.001 gravity defaults to 0
temperature_offset = 3 # add 3 degrees defaults to 0
```
